# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: insert.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'insert.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cinsert.proto\x12\ninsertword\")\n\x0bWordRequest\x12\x11\n\x04word\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_word\"D\n\x0cWordResponse\x12\x11\n\x04word\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03sum\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x07\n\x05_wordB\x06\n\x04_sum\"\x07\n\x05\x45mpty2\x8d\x01\n\nInsertWord\x12\x42\n\tListWords\x12\x17.insertword.WordRequest\x1a\x18.insertword.WordResponse\"\x00\x30\x01\x12;\n\x0bInsertCount\x12\x17.insertword.WordRequest\x1a\x11.insertword.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'insert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDREQUEST']._serialized_start=28
  _globals['_WORDREQUEST']._serialized_end=69
  _globals['_WORDRESPONSE']._serialized_start=71
  _globals['_WORDRESPONSE']._serialized_end=139
  _globals['_EMPTY']._serialized_start=141
  _globals['_EMPTY']._serialized_end=148
  _globals['_INSERTWORD']._serialized_start=151
  _globals['_INSERTWORD']._serialized_end=292
# @@protoc_insertion_point(module_scope)
