// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: insert.proto
#ifndef GRPC_insert_2eproto__INCLUDED
#define GRPC_insert_2eproto__INCLUDED

#include "insert.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

// Definição do serviço de inserção
class InsertWord final {
 public:
  static constexpr char const* service_full_name() {
    return "InsertWord";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Retorna a lista de palavras e sua ocorrência
    std::unique_ptr< ::grpc::ClientReaderInterface< ::WordResponse>> ListWords(::grpc::ClientContext* context, const ::WordRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::WordResponse>>(ListWordsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::WordResponse>> AsyncListWords(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::WordResponse>>(AsyncListWordsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::WordResponse>> PrepareAsyncListWords(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::WordResponse>>(PrepareAsyncListWordsRaw(context, request, cq));
    }
    // Insere uma palavra e conta sua ocorrência
    virtual ::grpc::Status InsertCount(::grpc::ClientContext* context, const ::WordRequest& request, ::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Empty>> AsyncInsertCount(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Empty>>(AsyncInsertCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Empty>> PrepareAsyncInsertCount(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Empty>>(PrepareAsyncInsertCountRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Retorna a lista de palavras e sua ocorrência
      virtual void ListWords(::grpc::ClientContext* context, const ::WordRequest* request, ::grpc::ClientReadReactor< ::WordResponse>* reactor) = 0;
      // Insere uma palavra e conta sua ocorrência
      virtual void InsertCount(::grpc::ClientContext* context, const ::WordRequest* request, ::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InsertCount(::grpc::ClientContext* context, const ::WordRequest* request, ::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::WordResponse>* ListWordsRaw(::grpc::ClientContext* context, const ::WordRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::WordResponse>* AsyncListWordsRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::WordResponse>* PrepareAsyncListWordsRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Empty>* AsyncInsertCountRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Empty>* PrepareAsyncInsertCountRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::WordResponse>> ListWords(::grpc::ClientContext* context, const ::WordRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::WordResponse>>(ListWordsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::WordResponse>> AsyncListWords(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::WordResponse>>(AsyncListWordsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::WordResponse>> PrepareAsyncListWords(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::WordResponse>>(PrepareAsyncListWordsRaw(context, request, cq));
    }
    ::grpc::Status InsertCount(::grpc::ClientContext* context, const ::WordRequest& request, ::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Empty>> AsyncInsertCount(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Empty>>(AsyncInsertCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Empty>> PrepareAsyncInsertCount(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Empty>>(PrepareAsyncInsertCountRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ListWords(::grpc::ClientContext* context, const ::WordRequest* request, ::grpc::ClientReadReactor< ::WordResponse>* reactor) override;
      void InsertCount(::grpc::ClientContext* context, const ::WordRequest* request, ::Empty* response, std::function<void(::grpc::Status)>) override;
      void InsertCount(::grpc::ClientContext* context, const ::WordRequest* request, ::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::WordResponse>* ListWordsRaw(::grpc::ClientContext* context, const ::WordRequest& request) override;
    ::grpc::ClientAsyncReader< ::WordResponse>* AsyncListWordsRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::WordResponse>* PrepareAsyncListWordsRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Empty>* AsyncInsertCountRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Empty>* PrepareAsyncInsertCountRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListWords_;
    const ::grpc::internal::RpcMethod rpcmethod_InsertCount_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Retorna a lista de palavras e sua ocorrência
    virtual ::grpc::Status ListWords(::grpc::ServerContext* context, const ::WordRequest* request, ::grpc::ServerWriter< ::WordResponse>* writer);
    // Insere uma palavra e conta sua ocorrência
    virtual ::grpc::Status InsertCount(::grpc::ServerContext* context, const ::WordRequest* request, ::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListWords() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListWords(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::grpc::ServerWriter< ::WordResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListWords(::grpc::ServerContext* context, ::WordRequest* request, ::grpc::ServerAsyncWriter< ::WordResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InsertCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InsertCount() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_InsertCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InsertCount(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInsertCount(::grpc::ServerContext* context, ::WordRequest* request, ::grpc::ServerAsyncResponseWriter< ::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListWords<WithAsyncMethod_InsertCount<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ListWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListWords() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::WordRequest, ::WordResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::WordRequest* request) { return this->ListWords(context, request); }));
    }
    ~WithCallbackMethod_ListWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListWords(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::grpc::ServerWriter< ::WordResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::WordResponse>* ListWords(
      ::grpc::CallbackServerContext* /*context*/, const ::WordRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_InsertCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InsertCount() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::WordRequest, ::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::WordRequest* request, ::Empty* response) { return this->InsertCount(context, request, response); }));}
    void SetMessageAllocatorFor_InsertCount(
        ::grpc::MessageAllocator< ::WordRequest, ::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::WordRequest, ::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_InsertCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InsertCount(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InsertCount(
      ::grpc::CallbackServerContext* /*context*/, const ::WordRequest* /*request*/, ::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ListWords<WithCallbackMethod_InsertCount<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListWords() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListWords(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::grpc::ServerWriter< ::WordResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InsertCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InsertCount() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_InsertCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InsertCount(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListWords() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListWords(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::grpc::ServerWriter< ::WordResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListWords(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InsertCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InsertCount() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_InsertCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InsertCount(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInsertCount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListWords() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->ListWords(context, request); }));
    }
    ~WithRawCallbackMethod_ListWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListWords(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::grpc::ServerWriter< ::WordResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* ListWords(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InsertCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InsertCount() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->InsertCount(context, request, response); }));
    }
    ~WithRawCallbackMethod_InsertCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InsertCount(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InsertCount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InsertCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_InsertCount() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::WordRequest, ::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::WordRequest, ::Empty>* streamer) {
                       return this->StreamedInsertCount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_InsertCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InsertCount(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInsertCount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::WordRequest,::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_InsertCount<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_ListWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_ListWords() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::WordRequest, ::WordResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::WordRequest, ::WordResponse>* streamer) {
                       return this->StreamedListWords(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_ListWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListWords(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::grpc::ServerWriter< ::WordResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedListWords(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::WordRequest,::WordResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_ListWords<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_ListWords<WithStreamedUnaryMethod_InsertCount<Service > > StreamedService;
};


#endif  // GRPC_insert_2eproto__INCLUDED
